### ISSUE TITLE
[FakeIdentities] slash unable to sync

### ISSUE THREAD

**Issue by Technetium1** [AAA3A-AAA3A/AAA3A-cogs#68]
### What cog is this bug report for?

FakeIdentities

### Describe the bug

1. `slash enable fakeidentity`
2. `slash sync`
3. failure to sync

### If there's an error, paste it here

```python
Exception in command 'slash sync':

Traceback (most recent call last):
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/redenv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 2413, in slash_sync
    raise e
  File "{HOME}/redenv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 2397, in slash_sync
    commands = await self.bot.tree.sync(guild=guild)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/redenv/lib/python3.11/site-packages/redbot/core/tree.py", line 158, in sync
    commands = await super().sync(*args, guild=guild, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1134, in sync
    raise CommandSyncFailure(e, commands) from None
discord.app_commands.errors.CommandSyncFailure: Failed to upload commands to Discord (HTTP status 400, error code 50035)
In command 'fakeidentity' defined in function 'FakeIdentities.fakeidentity'
  In parameter 'nationality'
    choices: Must be 25 or fewer in length.
  In parameter 'location'
    choices: Must be 25 or fewer in length.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "{HOME}/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 825, in invoke
    await super().invoke(ctx)
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1650, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: CommandSyncFailure: Failed to upload commands to Discord (HTTP status 400, error code 50035)
In command 'fakeidentity' defined in function 'FakeIdentities.fakeidentity'
  In parameter 'nationality'
    choices: Must be 25 or fewer in length.
  In parameter 'location'
    choices: Must be 25 or fewer in length.
```

**Comment by Technetium1** [comment]
Working well, thanks!
